server:
  port: 9090
  
  
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/sbms
    username: root
    password: root
    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          format_sql : true


############################## SMTP Props ######################################

#spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mahadevgade7@gmail.com
    password: vfkv yybz jezo absw
    properties:
      mail:
        smtp:
         auth: true
         starttls:
          enable: true



















       